name: Berlin Hack & Tell
description: Here you find a list of hacks and winners of Berlin Hack & Tell
url: http://berlinhackandtell.rocks
logo: /assets/logo.jpg
permalink: :year-:month-:day-:title
paginate: 100  #enables pagination, sets entries per page

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
